localhost: 123.57.131.180
server:
  port: 18083

spring:
  application:
    name: client-consumer

  ##  dubbo springboot ≈‰÷√
  dubbo:
    application:
      id: live-dubbo-consumer
      name: live-dubbo-consumer
    registry:
      address: zookeeper://${localhost}:2181